#!/bin/bash
# daily-token-counter.sh - Token aggregator with persistent historical data
# Reads current sessions + daily snapshots for accurate daily/weekly/monthly breakdown
# Zero Claude tokens. Pure bash + jq.

set -e

# Time ranges
TODAY=$(date -u '+%Y-%m-%d')
TODAY_DATE=$(date -u -d "$TODAY" '+%s')
WEEK_AGO=$(date -u -d "6 days ago" '+%Y-%m-%d')
MONTH_AGO=$(date -u -d "29 days ago" '+%Y-%m-%d')
HISTORY_DIR="/home/openclaw/.openclaw/workspace/token-history"

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Function to get pricing for a model
get_model_pricing() {
  local MODEL=$1
  case "$MODEL" in
    "claude-haiku-4-5")
      echo "0.0000008|0.000004|Claude Haiku 4.5 (\$0.80/M in, \$4.00/M out)"
      ;;
    "claude-sonnet-4-0")
      echo "0.000003|0.000015|Claude Sonnet 4.0 (\$3.00/M in, \$15.00/M out)"
      ;;
    "claude-opus-4-1")
      echo "0.000015|0.000075|Claude Opus 4.1 (\$15.00/M in, \$75.00/M out)"
      ;;
    *)
      echo "0.0000008|0.000004|Unknown Model"
      ;;
  esac
}

# Function to sum tokens from history files in a date range
sum_history_tokens() {
  local START_DATE=$1
  local END_DATE=$2
  
  local TOTAL_INPUT=0
  local TOTAL_OUTPUT=0
  
  # Find all history files in range
  for hist_file in "$HISTORY_DIR"/*.json; do
    [ -f "$hist_file" ] || continue
    FILE_DATE=$(basename "$hist_file" .json)
    
    # Check if file date is in range
    if [[ "$FILE_DATE" > "$START_DATE" || "$FILE_DATE" == "$START_DATE" ]] && [[ "$FILE_DATE" < "$END_DATE" || "$FILE_DATE" == "$END_DATE" ]]; then
      FILE_INPUT=$(jq -r '.inputTokens // 0' "$hist_file" 2>/dev/null || echo "0")
      FILE_OUTPUT=$(jq -r '.outputTokens // 0' "$hist_file" 2>/dev/null || echo "0")
      TOTAL_INPUT=$((TOTAL_INPUT + FILE_INPUT))
      TOTAL_OUTPUT=$((TOTAL_OUTPUT + FILE_OUTPUT))
    fi
  done
  
  echo "$TOTAL_INPUT|$TOTAL_OUTPUT"
}

# Function to display period stats
show_period_stats() {
  local PERIOD_NAME=$1
  local START_DATE=$2
  local END_DATE=$3
  local INPUT_COST=$4
  local OUTPUT_COST=$5
  
  IFS='|' read -r PERIOD_INPUT PERIOD_OUTPUT <<< "$(sum_history_tokens "$START_DATE" "$END_DATE")"
  PERIOD_TOKENS=$((PERIOD_INPUT + PERIOD_OUTPUT))
  PERIOD_COST=$(awk "BEGIN {printf \"%.4f\", $PERIOD_INPUT * $INPUT_COST + $PERIOD_OUTPUT * $OUTPUT_COST}")
  
  echo "  ${BLUE}${PERIOD_NAME}:${NC}"
  printf "    Input:  %10s | Output: %10s | Total: %10s | Cost: ${YELLOW}\$%s${NC}\n" "$PERIOD_INPUT" "$PERIOD_OUTPUT" "$PERIOD_TOKENS" "$PERIOD_COST"
}

# Get current sessions for today (live data)
SESSIONS_JSON=$(openclaw sessions list --json 2>/dev/null)
PRIMARY_MODEL=$(echo "$SESSIONS_JSON" | jq -r '.sessions[0].model // "unknown"')
IFS='|' read -r INPUT_COST OUTPUT_COST MODEL_NAME <<< "$(get_model_pricing "$PRIMARY_MODEL")"

# Get today's live session data
TODAY_LIVE_INPUT=$(echo "$SESSIONS_JSON" | jq '[.sessions[] | .inputTokens // 0] | add')
TODAY_LIVE_OUTPUT=$(echo "$SESSIONS_JSON" | jq '[.sessions[] | .outputTokens // 0] | add')

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 Token Usage Breakdown"
echo "🤖 Model: ${CYAN}$MODEL_NAME${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# TODAY (live data)
echo "  ${BLUE}TODAY (live):${NC}"
TODAY_TOKENS=$((TODAY_LIVE_INPUT + TODAY_LIVE_OUTPUT))
TODAY_COST=$(awk "BEGIN {printf \"%.4f\", $TODAY_LIVE_INPUT * $INPUT_COST + $TODAY_LIVE_OUTPUT * $OUTPUT_COST}")
printf "    Input:  %10s | Output: %10s | Total: %10s | Cost: ${YELLOW}\$%s${NC}\n" "$TODAY_LIVE_INPUT" "$TODAY_LIVE_OUTPUT" "$TODAY_TOKENS" "$TODAY_COST"

# WEEKLY (last 7 days from history)
show_period_stats "WEEKLY (last 7 days)" "$WEEK_AGO" "$TODAY" "$INPUT_COST" "$OUTPUT_COST"

# MONTHLY (last 30 days from history)
show_period_stats "MONTHLY (last 30 days)" "$MONTH_AGO" "$TODAY" "$INPUT_COST" "$OUTPUT_COST"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 History stored in: $HISTORY_DIR"
echo "Generated by bash (0 tokens)"
