#!/bin/bash
# tokens-command.sh - Telegram /tokens command handler

TOKEN_HISTORY_DIR="/home/openclaw/.openclaw/workspace/token-history"
PRICING_IN=1        # $1.00 per 1M input tokens (Haiku 4.5)
PRICING_OUT=5       # $5.00 per 1M output tokens (Haiku 4.5)

echo "📊 **Token Usage Breakdown**"
echo "🤖 **Model:** Claude Haiku 4.5 (\$1.00/M in, \$5.00/M out)"
echo ""

# TODAY (live)
today=$(date -u +%Y-%m-%d)
today_file="$TOKEN_HISTORY_DIR/${today}.json"

today_in=0
today_out=0

if [[ -f "$today_file" ]]; then
  today_in=$(jq '.inputTokens // 0' "$today_file" 2>/dev/null || echo 0)
  today_out=$(jq '.outputTokens // 0' "$today_file" 2>/dev/null || echo 0)
fi

today_total=$((today_in + today_out))
today_in_cost=$(echo "scale=4; $today_in * $PRICING_IN / 1000000" | bc)
today_out_cost=$(echo "scale=4; $today_out * $PRICING_OUT / 1000000" | bc)
today_cost=$(echo "scale=4; $today_in_cost + $today_out_cost" | bc)

echo "**TODAY (live):**"
echo "   Input: $today_in | Output: $today_out | Total: $today_total | Cost: \$$today_cost"
echo ""

# WEEKLY (last 7 days)
weekly_in=0
weekly_out=0

for i in {0..6}; do
  date_file="$TOKEN_HISTORY_DIR/$(date -u -d "-$i days" +%Y-%m-%d).json" 2>/dev/null
  if [[ -f "$date_file" ]]; then
    in=$(jq '.inputTokens // 0' "$date_file" 2>/dev/null || echo 0)
    out=$(jq '.outputTokens // 0' "$date_file" 2>/dev/null || echo 0)
    weekly_in=$((weekly_in + in))
    weekly_out=$((weekly_out + out))
  fi
done

weekly_total=$((weekly_in + weekly_out))
weekly_in_cost=$(echo "scale=4; $weekly_in * $PRICING_IN / 1000000" | bc)
weekly_out_cost=$(echo "scale=4; $weekly_out * $PRICING_OUT / 1000000" | bc)
weekly_cost=$(echo "scale=4; $weekly_in_cost + $weekly_out_cost" | bc)

echo "**WEEKLY (last 7 days):**"
echo "   Input: $weekly_in | Output: $weekly_out | Total: $weekly_total | Cost: \$$weekly_cost"
echo ""

# MONTHLY (last 30 days)
monthly_in=0
monthly_out=0

for i in {0..29}; do
  date_file="$TOKEN_HISTORY_DIR/$(date -u -d "-$i days" +%Y-%m-%d).json" 2>/dev/null
  if [[ -f "$date_file" ]]; then
    in=$(jq '.inputTokens // 0' "$date_file" 2>/dev/null || echo 0)
    out=$(jq '.outputTokens // 0' "$date_file" 2>/dev/null || echo 0)
    monthly_in=$((monthly_in + in))
    monthly_out=$((monthly_out + out))
  fi
done

monthly_total=$((monthly_in + monthly_out))
monthly_in_cost=$(echo "scale=4; $monthly_in * $PRICING_IN / 1000000" | bc)
monthly_out_cost=$(echo "scale=4; $monthly_out * $PRICING_OUT / 1000000" | bc)
monthly_cost=$(echo "scale=4; $monthly_in_cost + $monthly_out_cost" | bc)

echo "**MONTHLY (last 30 days):**"
echo "   Input: $monthly_in | Output: $monthly_out | Total: $monthly_total | Cost: \$$monthly_cost"
echo ""
echo "📁 History stored in: $TOKEN_HISTORY_DIR"
echo "Generated by bash (0 tokens)"
